# Исследование надежности заемщиков

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Описание-проекта" data-toc-modified-id="Описание-проекта-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Описание проекта</a></span></li><li><span><a href="#Обзор-данных" data-toc-modified-id="Обзор-данных-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Обзор данных</a></span><ul class="toc-item"><li><span><a href="#Выявление-пропусков" data-toc-modified-id="Выявление-пропусков-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Выявление пропусков</a></span></li><li><span><a href="#Проверка-данных-на-аномалии" data-toc-modified-id="Проверка-данных-на-аномалии-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Проверка данных на аномалии</a></span><ul class="toc-item"><li><span><a href="#Столбец-&quot;children&quot;" data-toc-modified-id="Столбец-&quot;children&quot;-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Столбец "children"</a></span></li><li><span><a href="#Столбец-&quot;days_employed&quot;" data-toc-modified-id="Столбец-&quot;days_employed&quot;-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Столбец "days_employed"</a></span></li><li><span><a href="#Столбец-&quot;dob_years&quot;" data-toc-modified-id="Столбец-&quot;dob_years&quot;-2.2.3"><span class="toc-item-num">2.2.3&nbsp;&nbsp;</span>Столбец "dob_years"</a></span></li></ul></li></ul></li><li><span><a href="#Обработка-данных" data-toc-modified-id="Обработка-данных-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Обработка данных</a></span><ul class="toc-item"><li><span><a href="#Столбец-&quot;total_income&quot;" data-toc-modified-id="Столбец-&quot;total_income&quot;-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Столбец "total_income"</a></span></li><li><span><a href="#Столбец-&quot;dob_years&quot;" data-toc-modified-id="Столбец-&quot;dob_years&quot;-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Столбец "dob_years"</a></span></li><li><span><a href="#Cтолбец-&quot;days_employed&quot;" data-toc-modified-id="Cтолбец-&quot;days_employed&quot;-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Cтолбец "days_employed"</a></span><ul class="toc-item"><li><span><a href="#Шаг-1" data-toc-modified-id="Шаг-1-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span>Шаг 1</a></span></li><li><span><a href="#Шаг-2" data-toc-modified-id="Шаг-2-3.3.2"><span class="toc-item-num">3.3.2&nbsp;&nbsp;</span>Шаг 2</a></span></li><li><span><a href="#Шаг-3" data-toc-modified-id="Шаг-3-3.3.3"><span class="toc-item-num">3.3.3&nbsp;&nbsp;</span>Шаг 3</a></span></li><li><span><a href="#Шаг-4" data-toc-modified-id="Шаг-4-3.3.4"><span class="toc-item-num">3.3.4&nbsp;&nbsp;</span>Шаг 4</a></span></li><li><span><a href="#Шаг-5" data-toc-modified-id="Шаг-5-3.3.5"><span class="toc-item-num">3.3.5&nbsp;&nbsp;</span>Шаг 5</a></span></li><li><span><a href="#Шаг-6" data-toc-modified-id="Шаг-6-3.3.6"><span class="toc-item-num">3.3.6&nbsp;&nbsp;</span>Шаг 6</a></span></li></ul></li><li><span><a href="#Cтолбец-&quot;children&quot;" data-toc-modified-id="Cтолбец-&quot;children&quot;-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Cтолбец "children"</a></span></li><li><span><a href="#Изменение-типов-данных" data-toc-modified-id="Изменение-типов-данных-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Изменение типов данных</a></span></li><li><span><a href="#Удаление-дубликатов" data-toc-modified-id="Удаление-дубликатов-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Удаление дубликатов</a></span><ul class="toc-item"><li><span><a href="#Полные-дубликаты" data-toc-modified-id="Полные-дубликаты-3.6.1"><span class="toc-item-num">3.6.1&nbsp;&nbsp;</span>Полные дубликаты</a></span></li><li><span><a href="#Неявные-дубликаты" data-toc-modified-id="Неявные-дубликаты-3.6.2"><span class="toc-item-num">3.6.2&nbsp;&nbsp;</span>Неявные дубликаты</a></span><ul class="toc-item"><li><span><a href="#Столбец-&quot;education&quot;" data-toc-modified-id="Столбец-&quot;education&quot;-3.6.2.1"><span class="toc-item-num">3.6.2.1&nbsp;&nbsp;</span>Столбец "education"</a></span></li><li><span><a href="#Столбец-&quot;family_status&quot;" data-toc-modified-id="Столбец-&quot;family_status&quot;-3.6.2.2"><span class="toc-item-num">3.6.2.2&nbsp;&nbsp;</span>Столбец "family_status"</a></span></li><li><span><a href="#Столбец-&quot;gender&quot;" data-toc-modified-id="Столбец-&quot;gender&quot;-3.6.2.3"><span class="toc-item-num">3.6.2.3&nbsp;&nbsp;</span>Столбец "gender"</a></span></li><li><span><a href="#Столбец-&quot;income_type&quot;." data-toc-modified-id="Столбец-&quot;income_type&quot;.-3.6.2.4"><span class="toc-item-num">3.6.2.4&nbsp;&nbsp;</span>Столбец "income_type".</a></span></li><li><span><a href="#Столбец-&quot;debt&quot;" data-toc-modified-id="Столбец-&quot;debt&quot;-3.6.2.5"><span class="toc-item-num">3.6.2.5&nbsp;&nbsp;</span>Столбец "debt"</a></span></li><li><span><a href="#Столбец-&quot;purpose&quot;" data-toc-modified-id="Столбец-&quot;purpose&quot;-3.6.2.6"><span class="toc-item-num">3.6.2.6&nbsp;&nbsp;</span>Столбец "purpose"</a></span></li></ul></li></ul></li><li><span><a href="#Формирование-дополнительных-датафреймов-словарей" data-toc-modified-id="Формирование-дополнительных-датафреймов-словарей-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>Формирование дополнительных датафреймов-словарей</a></span></li><li><span><a href="#Категоризация-дохода" data-toc-modified-id="Категоризация-дохода-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>Категоризация дохода</a></span></li><li><span><a href="#Категоризация-целей-кредита" data-toc-modified-id="Категоризация-целей-кредита-3.9"><span class="toc-item-num">3.9&nbsp;&nbsp;</span>Категоризация целей кредита</a></span></li></ul></li><li><span><a href="#Ответы-на-вопросы" data-toc-modified-id="Ответы-на-вопросы-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Ответы на вопросы</a></span><ul class="toc-item"><li><span><a href="#Вопрос-1" data-toc-modified-id="Вопрос-1-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Вопрос 1</a></span></li><li><span><a href="#Вопрос-2" data-toc-modified-id="Вопрос-2-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Вопрос 2</a></span></li><li><span><a href="#Вопрос-3" data-toc-modified-id="Вопрос-3-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Вопрос 3</a></span></li><li><span><a href="#Вопрос-4" data-toc-modified-id="Вопрос-4-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Вопрос 4</a></span></li></ul></li><li><span><a href="#Общие-выводы" data-toc-modified-id="Общие-выводы-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Общие выводы</a></span></li></ul></div>

## Описание проекта

Кредитному отделу банка необходимо выяснить, влияет ли семейное положение и количество детей у заёмщика, а также уровень его дохода и цель кредитования - на факт погашения кредита в срок. Результаты исследования будут учтены при построении модели кредитного скоринга — специальной системы, которая оценивает способность потенциального заёмщика вернуть кредит банку.

## Обзор данных

Для начала работы нам необходимо импортировать библиотеку для работы с табличными данными "Pandas" и открыть csv-файл.

In [1]:
# Импортируем библиотеку Pandas.

import pandas as pd

In [2]:
# Открываем csv-файл с таблицей и сохраняем в переменной data.

data = pd.read_csv('datasets/data.csv')

In [3]:
# Получаем первые 5 строк таблицы.

data.head()

children  days_employed  dob_years education  education_id  \
0         1   -8437.673028         42    высшее             0   
1         1   -4024.803754         36   среднее             1   
2         0   -5623.422610         33   Среднее             1   
3         3   -4124.747207         32   среднее             1   
4         0  340266.072047         53   среднее             1   

      family_status  family_status_id gender income_type  debt   total_income  \
0   женат / замужем                 0      F   сотрудник     0  253875.639453   
1   женат / замужем                 0      F   сотрудник     0  112080.014102   
2   женат / замужем                 0      M   сотрудник     0  145885.952297   
3   женат / замужем                 0      M   сотрудник     0  267628.550329   
4  гражданский брак                 1      F   пенсионер     0  158616.077870   

                      purpose  
0               покупка жилья  
1     приобретение автомобиля  
2               покупка жилья  
3  дополнительное образование  
4             сыграть свадьбу

In [4]:
# Получаем общую информацию по таблице.

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


### Выявление пропусков

В двух столбцах: с данными об общем трудовом стаже ("days_employed") и ежемесячном доходе ("total_income") 
есть пропущенные данные, причем одинаковое количество.

Теоретически, причинами отсутствия данных могли бы быть:

а) случайные технические сбои в банковской программе - вероятность этого невысока, так как данные, судя по всему, отсутствуют в одних и тех же строках двух столбцов;

б) отсутствие у заемщика трудового стажа и, соответственно, дохода - это тоже маловероятно, особенно, учитывая, что тип занятости и возраст у этих заемщиков самый разный, и что банк не предоставил бы кредит при отсутствии дохода;

в) невнесение своевременно сотрудником банка данных о заемщике в базу - такое возможно, если кредит пока находится в стадии оформления;

г) непредоставление клиентом полного пакета документов - также возможно, например, если для определенных заемщиков подтверждение дохода не требуется.

Проверим, действительно ли данные отсутствуют в одних и тех же строках этих двух столбцов.

In [5]:
# Выясняем, сколько в таблице строк, 
# где в столбцах "days_employed" и "total_income" одновременно непустые значения.

data[(data['days_employed'].notna()) & (data['total_income'].notna())].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19351 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          19351 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         19351 non-null  int64  
 3   education         19351 non-null  object 
 4   education_id      19351 non-null  int64  
 5   family_status     19351 non-null  object 
 6   family_status_id  19351 non-null  int64  
 7   gender            19351 non-null  object 
 8   income_type       19351 non-null  object 
 9   debt              19351 non-null  int64  
 10  total_income      19351 non-null  float64
 11  purpose           19351 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 1.9+ MB


Гипотеза подтвердилась. Если в одном из указанных столбцов стоит пустое значение, то и во втором оно пустое. В противном случае общих строк было бы меньше, чем 19351.

Проверим, разные ли типы занятости и возрасты у заемщиков с пустыми значениями стажа и дохода.

In [6]:
# Выясняем, какие типы занятости у заемщиков, чьи стаж и доходы не указаны в таблице.
# Слева - тип занятости, справа - количество таких заемщиков.

data[(data['days_employed'].isna()) & (data['total_income'].isna())]['income_type'].value_counts()

сотрудник          1105
компаньон           508
пенсионер           413
госслужащий         147
предприниматель       1
Name: income_type, dtype: int64

In [7]:
# Выясняем, какой возраст у заемщиков, чьи стаж и доходы не указаны в таблице.
# Слева - возраст, справа - количество таких заемщиков.

data[(data['days_employed'].isna()) & (data['total_income'].isna())]['dob_years'].value_counts().sort_index()

0     10
19     1
20     5
21    18
22    17
23    36
24    21
25    23
26    35
27    36
28    57
29    50
30    58
31    65
32    37
33    51
34    69
35    64
36    63
37    53
38    54
39    51
40    66
41    59
42    65
43    50
44    44
45    50
46    48
47    59
48    46
49    50
50    51
51    50
52    53
53    44
54    55
55    48
56    54
57    56
58    56
59    34
60    39
61    38
62    38
63    29
64    37
65    20
66    20
67    16
68     9
69     5
70     3
71     5
72     2
73     1
Name: dob_years, dtype: int64

Для наглядности посмотрим на таблицу, в которой отобраны строки с пустыми значениями.

In [8]:
# Смотрим 5 случайных строк полученной таблицы.

data[(data['days_employed'].isna())].sample(5)

children  days_employed  dob_years education  education_id  \
9542          1            NaN         36   среднее             1   
21305         0            NaN         59   среднее             1   
15796         0            NaN         30   среднее             1   
18009         2            NaN         34   среднее             1   
14639         1            NaN         32   среднее             1   

               family_status  family_status_id gender income_type  debt  \
9542         женат / замужем                 0      F   сотрудник     0   
21305  Не женат / не замужем                 4      F   пенсионер     0   
15796        женат / замужем                 0      F   сотрудник     0   
18009       гражданский брак                 1      F   сотрудник     0   
14639        женат / замужем                 0      F   сотрудник     0   

       total_income                                 purpose  
9542            NaN                       операции с жильем  
21305           NaN  строительство собственной недвижимости  
15796           NaN                   получение образования  
18009           NaN                      высшее образование  
14639           NaN                    покупка недвижимости

Гипотеза подтвердилась. Тип занятости у таких заемщиков самый разный, среди них есть и работающие, и пенсионеры. То же касается и возрастов.

Теперь найдем, какую долю составляют пропущенные значения в каждом из двух столбцов с пропусками.

In [9]:
# Вычисляем отношение числа пустых ячеек к общему числу ячеек. 

empty_cells_percentage = data['days_employed'].isna().mean()
print(f'Пустых ячеек в столбцах "days_employed" и "total_income": {empty_cells_percentage:.2%}.')

Пустых ячеек в столбцах "days_employed" и "total_income": 10.10%.


В обоих столбцах не хватает примерно по 10% данных. Это существенно, чтобы повлиять на результаты исследования. Поэтому заполним отсутствие данных медианным значением.

Но пока сделаем это только с данными о доходах, поскольку в трудовом стаже есть отрицательные значения. Их еще предстоит исправить, иначе расчет будет искаженным.

In [10]:
# Находим медианное значение доходов заемщиков.

income_median = data['total_income'].median()
print(f'Медианное значение доходов составляет: {income_median:.2f}.')

Медианное значение доходов составляет: 145017.94.


Однако доходы разных категорий заемщиков могут отличаться. Соответственно, целесообразнее будет рассчитать медианные значения по каждому типу занятости отдельно.

In [11]:
# Группируем заемщиков по типу занятости и выводим медианные значения доходов по каждому типу.

income_type_categories = data.groupby('income_type')['total_income'].median().sort_values()
income_type_categories

income_type
в декрете           53829.130729
студент             98201.625314
пенсионер          118514.486412
безработный        131339.751676
сотрудник          142594.396847
госслужащий        150447.935283
компаньон          172357.950966
предприниматель    499163.144947
Name: total_income, dtype: float64

Как видим, средние значения доходов "сотрудников", "компаньонов", "пенсионеров" и "госслужащих" близки к общей средней. Учитывая, что больше всего пропусков приходится именно на эти категории, мы могли бы заменить все пропуски в доходах на общее среднее значение. Это не сильно бы повлияло на результаты анализа.

Однако все же для большей точности сделаем замены отдельно по каждой из этих категорий.

Но сделаем это после проверки данных на аномалии.

### Проверка данных на аномалии

Итак, прежде всего, названия столбцов. Они приведены в нижнем регистре, с соблюдением нужного стиля. Из названий понятно содержимое столбцов. Тут можно ничего не менять.

Рассмотрим распределение числовых данных в таблице.

In [12]:
# Выводим описание столбцов с количественными данными.

data.describe()

children  days_employed     dob_years  education_id  \
count  21525.000000   19351.000000  21525.000000  21525.000000   
mean       0.538908   63046.497661     43.293380      0.817236   
std        1.381587  140827.311974     12.574584      0.548138   
min       -1.000000  -18388.949901      0.000000      0.000000   
25%        0.000000   -2747.423625     33.000000      1.000000   
50%        0.000000   -1203.369529     42.000000      1.000000   
75%        1.000000    -291.095954     53.000000      1.000000   
max       20.000000  401755.400475     75.000000      4.000000   

       family_status_id          debt  total_income  
count      21525.000000  21525.000000  1.935100e+04  
mean           0.972544      0.080883  1.674223e+05  
std            1.420324      0.272661  1.029716e+05  
min            0.000000      0.000000  2.066726e+04  
25%            0.000000      0.000000  1.030532e+05  
50%            0.000000      0.000000  1.450179e+05  
75%            1.000000      0.000000  2.034351e+05  
max            4.000000      1.000000  2.265604e+06

Сразу выявляются следующие аномалии:

1. Минимальное значение количества детей (столбец "children") - отрицательное (-1). Возможно, опечатка сотруника банка.


2. Максимальное значение количества детей (тот же столбец) - 20. Также может быть случайной ошибкой сотрудника.


3. В столбце с данными о стаже ("days_employed") есть отрицательные значения. Возможно, знак минуса тоже стоит по ошибке.


4. Максимальное значение по тому же столбцу слишком большое (около 1100 лет). Возможно, проблема не в отдельных выдающихся значениях, а во всем столбце в целом, т.к. среднее значение тоже не вписывается в рамки нормы (более 170 лет). Если у отрицательных значений убрать знаки минуса, среднее вырастет еще больше.


5. Минимальное значение возраста (столбец "dob_years") равно 0. Возможно, возраст не указан, или же снова опечатка.

Проверим отдельно каждый из названных столбцов.

#### Столбец "children"

In [13]:
# Выводим уникальные значения в столбце "children". 
# Слева - количество детей у заемщиков, справа - число таких случаев.

print(data['children'].value_counts())

 0     14149
 1      4818
 2      2055
 3       330
 20       76
-1        47
 4        41
 5         9
Name: children, dtype: int64


Судя по информации, подавляющее большинство заемщиков не имеют детей. Втрое меньше заемщиков с одним ребенком. 
Дальнейшие данные не вызывают вопросов, кроме 47 заемщиков с числом детей, равным -1, а также 76 заемщиков, у которых по 20 детей.

Попробуем найти какие-либо закономерности в наличии этих аномальных данных в таблице.

In [14]:
# Выводим строки таблицы, где количество детей равно -1 (первые 10 таких строк).

data[data['children'] == -1].head(10)

children  days_employed  dob_years education  education_id  \
291         -1   -4417.703588         46   среднее             1   
705         -1    -902.084528         50   среднее             1   
742         -1   -3174.456205         57   среднее             1   
800         -1  349987.852217         54   среднее             1   
941         -1            NaN         57   Среднее             1   
1363        -1   -1195.264956         55   СРЕДНЕЕ             1   
1929        -1   -1461.303336         38   среднее             1   
2073        -1   -2539.761232         42   среднее             1   
3814        -1   -3045.290443         26   Среднее             1   
4201        -1    -901.101738         41   среднее             1   

              family_status  family_status_id gender  income_type  debt  \
291        гражданский брак                 1      F    сотрудник     0   
705         женат / замужем                 0      F  госслужащий     0   
742         женат / замужем                 0      F    сотрудник     0   
800   Не женат / не замужем                 4      F    пенсионер     0   
941         женат / замужем                 0      F    пенсионер     0   
1363        женат / замужем                 0      F    компаньон     0   
1929  Не женат / не замужем                 4      M    сотрудник     0   
2073              в разводе                 3      F    компаньон     0   
3814       гражданский брак                 1      F  госслужащий     0   
4201        женат / замужем                 0      F  госслужащий     0   

       total_income                          purpose  
291   102816.346412           профильное образование  
705   137882.899271          приобретение автомобиля  
742    64268.044444       дополнительное образование  
800    86293.724153       дополнительное образование  
941             NaN     на покупку своего автомобиля  
1363   69550.699692           профильное образование  
1929  109121.569013                    покупка жилья  
2073  162638.609373                    покупка жилья  
3814  131892.785435            на проведение свадьбы  
4201  226375.766751  операции со своей недвижимостью

In [15]:
# Выводим строки таблицы, где количество детей равно 20 (первые 10 таких строк).

data[data['children'] == 20].head(10)

children  days_employed  dob_years education  education_id  \
606         20    -880.221113         21   среднее             1   
720         20    -855.595512         44   среднее             1   
1074        20   -3310.411598         56   среднее             1   
2510        20   -2714.161249         59    высшее             0   
2941        20   -2161.591519          0   среднее             1   
3302        20            NaN         35   среднее             1   
3396        20            NaN         56    высшее             0   
3671        20    -913.161503         23   среднее             1   
3697        20   -2907.910616         40   среднее             1   
3735        20    -805.044438         26    высшее             0   

              family_status  family_status_id gender  income_type  debt  \
606         женат / замужем                 0      M    компаньон     0   
720         женат / замужем                 0      F    компаньон     0   
1074        женат / замужем                 0      F    сотрудник     1   
2510         вдовец / вдова                 2      F    сотрудник     0   
2941        женат / замужем                 0      F    сотрудник     0   
3302  Не женат / не замужем                 4      F  госслужащий     0   
3396        женат / замужем                 0      F    компаньон     0   
3671  Не женат / не замужем                 4      F    сотрудник     0   
3697       гражданский брак                 1      M    сотрудник     0   
3735  Не женат / не замужем                 4      M    сотрудник     0   

       total_income                                purpose  
606   145334.865002                          покупка жилья  
720   112998.738649                   покупка недвижимости  
1074  229518.537004                  получение образования  
2510  264474.835577  операции с коммерческой недвижимостью  
2941  199739.941398                  на покупку автомобиля  
3302            NaN                 профильное образование  
3396            NaN                     высшее образование  
3671  101255.492076     на покупку подержанного автомобиля  
3697  115380.694664     на покупку подержанного автомобиля  
3735  137200.646181                           ремонт жилью

Визуально никаких связей и закономерностей не выявлено. 


_Вывод:_

В обоих случаях, возможно, имело место случайное нажатие лишних клавиш.

Однако в случае со значением "20" это более очевидно, т.к. "2" и "0" на боковой клавиатуре находятся рядом. Одна из цифр лишняя. И, поскольку, первой нажата цифра "2", то более вероятно, что намеревались нажать именно ее (а не ноль).

С отрицательной единицей не так однозначно, т.к. знак минуса/тире/дефиса далеко от "1".


Ввиду того, что эти данные практически не повлияют на результат анализа, будем исходить из общей целесообразности.
1. Значения "20" заменим на "2".
2. Строки с "-1" удалим.


Вернемся к этому после обработки столбцов "days_employed" и "dob_years".

#### Столбец "days_employed"

__1.__ Выясним количество строк, где значения в этом столбце отрицательные.

In [16]:
# Находим число строк с отрицательными значениями стажа, а также их долю от всех непустых его значений в процентах.

negative_days_employed = data[data['days_employed'] < 0]['days_employed'].count()
print("Отрицательных значений стажа -", negative_days_employed)
print(f'Доля отрицательных значений стажа в общем числе непустых значений - '
      f'{(negative_days_employed / data.loc[data["days_employed"].notna(), "days_employed"].count()):.0%}')

Отрицательных значений стажа - 15906
Доля отрицательных значений стажа в общем числе непустых значений - 82%


Доля отрицательных значений слишком существенна, чтобы ее можно было игнорировать.

Найдем среди них максимальный стаж, выраженный в годах, если не брать в расчет знак минуса.

In [17]:
print(f"Максимальное по модулю значение стажа (среди отрицательных) - "
      f"{(data[data['days_employed'] < 0]['days_employed'].min() / (-365)):.2f} лет")

Максимальное по модулю значение стажа (среди отрицательных) - 50.38 лет


Возможная причина наличия отрицательных данных - случайный ввод минуса/дефиса/тире перед числовыми значениями.

Просмотрим некоторые отрицательные значения из этого столбца, предварительно поменяв знак и переведя в годы.

In [18]:
# Выводим те значения трудового стажа, которые стоят со знаком минус, в годах и по модулю (первые 10 строк).

data[data['days_employed'] < 0]['days_employed'].head(10) / -365

0     23.116912
1     11.026860
2     15.406637
3     11.300677
5      2.537495
6      7.888225
7      0.418574
8     18.985932
9      5.996593
10    11.428722
Name: days_employed, dtype: float64

Попробуем сравнить полученные значения с возрастом заемщиков, отняв из первого второе.

In [19]:
# Находим диапазон возрастов трудоустройства этих заемщиков.

employment_age = data[data['days_employed'] < 0]['dob_years'] - (data[data['days_employed'] < 0]['days_employed'] / (-365))

print(f"Минимальный возраст трудоустройства заемщика - {employment_age.min():.2f} лет")
print(f"Максимальный возраст трудоустройства заемщика - {employment_age.max():.2f} лет")

Минимальный возраст трудоустройства заемщика - -29.29 лет
Максимальный возраст трудоустройства заемщика - 70.40 лет


_Вывод:_

В целом, данные без знака минуса похожи на значения стажа. Но мы получаем отрицательный возраст для начала трудового стажа у значительной доли заемщиков.



Необходимо сначала проверить данные о возрасте заемщиков. Вернемся к этому вопросу после обработки стоблца "dob_years".


__2.__ Теперь выясним количество строк, где значения в столбце "days_employed" слишком большие.

In [20]:
# Находим число строк с неотрицательными значениями стажа.

print("Неотрицательных значений стажа -", data[data['days_employed'] >= 0]['days_employed'].count())

Неотрицательных значений стажа - 3445


Есть минимум два предположения насчет причины наличия больших значений:

1. Возможно, стаж указан не в днях, а в других единицах. Это предстоит проверить.

2. Или же сотрудник банка мог просто, в целях экономии времени, заносить беспорядочно большие числа, в случае если стаж у заемщика был больше необходимого или не имел особого значения.

Выясним, какие из этих значений выбиваются из рамок реальности.

In [21]:
# Находим минимальное неотрицательное количество лет стажа.

print(f"Минимальное неотрицательное значение стажа - "
      f"{(data[data['days_employed'] >= 0]['days_employed'].min() / 365):.2f} лет")

Минимальное неотрицательное значение стажа - 900.63 лет


Проверим еще раз, найдя количество значений стажа со сроком более 900 лет.

In [22]:
# Находим число строк со значениями стажа более 900 лет.

print("Слишком больших значений стажа -", data[data['days_employed'] > (900 * 365)]['days_employed'].count())

Слишком больших значений стажа - 3445


In [23]:
# Находим максимальное количество лет стажа.

print(f"Максимальное значение стажа - {(data[data['days_employed'] >= 0]['days_employed'].max() / 365):.2f} лет")

Максимальное значение стажа - 1100.70 лет


Выясним, связан ли тип занятости с наличием больших значений в стаже.

In [24]:
# Смотрим количество сотрудников, у которых указан стаж более 900 лет.

data[data['days_employed'] > (900 * 365)]['income_type'].value_counts()

пенсионер      3443
безработный       2
Name: income_type, dtype: int64

In [25]:
# Смотрим количество сотрудников, у которых указан отрицательный стаж.

data[data['days_employed'] < 0]['income_type'].value_counts()

сотрудник          10014
компаньон           4577
госслужащий         1312
студент                1
предприниматель        1
в декрете              1
Name: income_type, dtype: int64

_Вывод:_

Все положительные значения стажа лежат в диапазоне от 900 до 1100 лет.

Практически все заемщики, у которых указан слишком большой стаж, - пенсионеры.
При этом ни у одного пенсионера нет отрицательного стажа.

Ввиду отсутствия возможности выяснить действительную причину, усматривается два варианта действий:

1. Простой вариант. 
Возможно, данные указаны не в днях, а, например, в часах. Тогда вместо 900 - 1100 лет мы получаем 37.5 - 45.8  лет.


2. Дополнительный вариант.
Заменяем все положительные значения на максимальный стаж, предположительно считающийся таковым в данном кредитном учреждении.
После этого считаем среднее значение у всех заемщиков с отрицательным стажем. По нему выясняем их средний возраст трудоустройства. Используем затем этот же возраст трудоустройства для расчета стажа пенсионеров и безработных.


И в том, и в другом случае учитываем, что там, где разница между возрастом и стажем меньше минимального возраста трудоустройства (например, 18 лет), желательно корректировать значение стажа.

Опробуем оба варианта и выберем наиболее оптимальный. Сделаем это в пункте "Обработка данных".

#### Столбец "dob_years"

Просмотрим уникальные значения возрастов.

In [26]:
# Выводим уникальные значения возрастов, отсортированных в порядке их возрастания.
# Слева - возраст, справа - число заемщиков такого возраста.

data['dob_years'].value_counts().sort_index()

0     101
19     14
20     51
21    111
22    183
23    254
24    264
25    357
26    408
27    493
28    503
29    545
30    540
31    560
32    510
33    581
34    603
35    617
36    555
37    537
38    598
39    573
40    609
41    607
42    597
43    513
44    547
45    497
46    475
47    480
48    538
49    508
50    514
51    448
52    484
53    459
54    479
55    443
56    487
57    460
58    461
59    444
60    377
61    355
62    352
63    269
64    265
65    194
66    183
67    167
68     99
69     85
70     65
71     58
72     33
73      8
74      6
75      1
Name: dob_years, dtype: int64

Если не считать нулевого значения возраста, остальные распределены нормально.

Выясним тип занятости у заемщиков с возрастом "0".

In [27]:
# Выводим строки таблицы, где указан нулевой возраст заемщиков (случайных 5 строк).

data[data['dob_years'] == 0].sample(5)

children  days_employed  dob_years education  education_id  \
13968         1   -1018.525283          0   среднее             1   
578           0  397856.565013          0   среднее             1   
3044          2   -2502.891798          0    высшее             0   
18539         0   -4852.175654          0    Высшее             0   
1890          0            NaN          0    высшее             0   

               family_status  family_status_id gender income_type  debt  \
13968        женат / замужем                 0      F   сотрудник     1   
578          женат / замужем                 0      F   пенсионер     0   
3044   Не женат / не замужем                 4      M   сотрудник     0   
18539  Не женат / не замужем                 4      M   компаньон     0   
1890   Не женат / не замужем                 4      F   сотрудник     0   

        total_income                                 purpose  
13968  155341.706429                         свой автомобиль  
578     97620.687042  строительство собственной недвижимости  
3044   292145.267076                операции с недвижимостью  
18539  254837.819494                           покупка жилья  
1890             NaN                                   жилье

Как видно из таблицы, заемщики с таким значением возраста относятся к самым разным типам занятости.

_Вывод:_

Поскольку особой закономерности тут не прослеживается, и таких строк в общей таблице менее 0.5% (101 из 21525), то их можно как удалить, так и обновить, заменив нулевые данные средними по категориям заемщиков (типу занятости).
Ни то, ни другое на результаты существенно не повлияет.

## Обработка данных

### Столбец "total_income"

Начнем с заполнения пустых ячеек в столбце.

In [28]:
# Заполняем пустые ячейки столбца с доходами медианными значениями по каждой категории заемщиков (по типу занятости).
# Выводим информацию о датафрейме.

data_by_income = data.groupby('income_type')['total_income'].transform('median')
data['total_income'] = data['total_income'].fillna(data_by_income)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      21525 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


Таким образом, пустых ячеек в столбце "total_income" не осталось.

Проверим, действительно ли они заполнились соответствующими средними значениями.

In [29]:
# Выводим строки таблицы со все еще пустыми ячейками в столбце "days_employed" (первые 5 строк).

data[(data['days_employed'].isna())].head()

children  days_employed  dob_years education  education_id  \
12         0            NaN         65   среднее             1   
26         0            NaN         41   среднее             1   
29         0            NaN         63   среднее             1   
41         0            NaN         50   среднее             1   
55         0            NaN         54   среднее             1   

            family_status  family_status_id gender  income_type  debt  \
12       гражданский брак                 1      M    пенсионер     0   
26        женат / замужем                 0      M  госслужащий     0   
29  Не женат / не замужем                 4      F    пенсионер     0   
41        женат / замужем                 0      F  госслужащий     0   
55       гражданский брак                 1      F    пенсионер     1   

     total_income                           purpose  
12  118514.486412                   сыграть свадьбу  
26  150447.935283                       образование  
29  118514.486412  строительство жилой недвижимости  
41  150447.935283  сделка с подержанным автомобилем  
55  118514.486412                   сыграть свадьбу

Как видим, таблица заполнилась верно.

### Столбец "dob_years"

Заменим нулевые значения возрастов средними по группам.

In [30]:
# Меняем все значения возраста заемщиков, равные нулю, на соответствующие средние значения
# по каждой категории заемщиков (по типу занятости).
# После чего проверяем количество оставшихся нулевых значений.

data['dob_years'] = data.groupby('income_type')['dob_years'].transform(lambda x: x.replace(0, int(x.mean())))

print("Количество нулевых значений в столбце 'dob_years' -", data[data['dob_years'] == 0]['dob_years'].count())

Количество нулевых значений в столбце 'dob_years' - 0


Все нулевые значения заменены.

### Cтолбец "days_employed"

Хотя в целях настоящего проекта можно в принципе игнорировать этот столбец (его данные никак не помогут в ответе на поставленные вопросы), однако в качестве примера поиска путей решения при обработке подобных данных остановимся на нем подробнее.

#### Шаг 1

Итак, реализуем оба варианта замены данных о стаже. При этом создадим дублирующие датафреймы, чтобы пока не трогать основной.

__Вариант 1.__

In [31]:
# Создаем копию датафрейма для проверки Варианта 1.

data0 = data.copy()

In [32]:
# Делим все положительные значения трудового стажа на 24 часа, чтобы получить значения в днях.
# Берем все отрицательные значения трудового стажа по модулю.
# Выводим первые 10 строк обновленной таблицы.

data0.loc[data0['days_employed'] > 0,'days_employed'] = data0['days_employed'] / 24
data0.loc[data0['days_employed'] < 0,'days_employed'] = - data0['days_employed']

data0.head(10)

children  days_employed  dob_years education  education_id  \
0         1    8437.673028         42    высшее             0   
1         1    4024.803754         36   среднее             1   
2         0    5623.422610         33   Среднее             1   
3         3    4124.747207         32   среднее             1   
4         0   14177.753002         53   среднее             1   
5         0     926.185831         27    высшее             0   
6         0    2879.202052         43    высшее             0   
7         0     152.779569         50   СРЕДНЕЕ             1   
8         2    6929.865299         35    ВЫСШЕЕ             0   
9         0    2188.756445         41   среднее             1   

      family_status  family_status_id gender income_type  debt   total_income  \
0   женат / замужем                 0      F   сотрудник     0  253875.639453   
1   женат / замужем                 0      F   сотрудник     0  112080.014102   
2   женат / замужем                 0      M   сотрудник     0  145885.952297   
3   женат / замужем                 0      M   сотрудник     0  267628.550329   
4  гражданский брак                 1      F   пенсионер     0  158616.077870   
5  гражданский брак                 1      M   компаньон     0  255763.565419   
6   женат / замужем                 0      F   компаньон     0  240525.971920   
7   женат / замужем                 0      M   сотрудник     0  135823.934197   
8  гражданский брак                 1      F   сотрудник     0   95856.832424   
9   женат / замужем                 0      M   сотрудник     0  144425.938277   

                      purpose  
0               покупка жилья  
1     приобретение автомобиля  
2               покупка жилья  
3  дополнительное образование  
4             сыграть свадьбу  
5               покупка жилья  
6           операции с жильем  
7                 образование  
8       на проведение свадьбы  
9     покупка жилья для семьи

Необходимо откорректировать стаж, чтобы возраст трудоустройства вернулся в рамки. Будем исходить из того, что трудиться разрешается с 18 лет.

Поэтому, если разница между возрастом заемщика (в годах) и его стажем составила менее 18 лет, необходимо указать стаж, равный разнице между возрастом (в днях) и 18 годами (6570 днями).

In [33]:
# Обновляем возраст тех, у кого стаж получается нереально большим, так чтобы возраст трудоустройства не был больше 18 лет.
# Выводим данные о минимальном, среднем и максимальном возрасте трудоустройства заемщиков.

data0.loc[((data0['dob_years'] - data0['days_employed'] / 365) < 18),
          'days_employed'] = data0['dob_years'] * 365 - 18 * 365

employment_age0 = data0['dob_years'] - data0['days_employed'] / 365

# РЕЗУЛЬТАТ ПО ВАРИАНТУ 1
print(f"Минимальный возраст трудоустройства заемщика - {employment_age0.min():.2f} лет")  # 18.00 лет
print(f"Средний возраст трудоустройства заемщика - {employment_age0.mean():.2f} лет")     # 31.25 лет
print(f"Максимальный возраст трудоустройства заемщика - {employment_age0.max():.2f} лет") # 70.40 лет

Минимальный возраст трудоустройства заемщика - 18.00 лет
Средний возраст трудоустройства заемщика - 31.25 лет
Максимальный возраст трудоустройства заемщика - 70.40 лет


#### Шаг 2

__Вариант 2a.__

In [34]:
# Создаем копию датафрейма для проверки Варианта 2а.

data1 = data.copy()

Т.к. максимальное по модулю значение стажа (среди отрицательных) - 50.38 лет, как было выяснено ранее, округлим и примем за максимально установленный стаж 50 лет.

Заменим содержимое всех ячеек с положительным значением стажа на 18250 (т.е. 50x365) и проверим, как стаж соотносится с возрастом.

In [35]:
# Заменяем все положительные значения трудового стажа на 18250 дней (т.е. 50 лет).
# Выводим строки с получившимися значениями стажа (первые 10 таких строк).

data1.loc[data1['days_employed'] > 0,'days_employed'] = 50 * 365

data1[data1['days_employed'] > 0].head()

children  days_employed  dob_years education  education_id  \
4          0        18250.0         53   среднее             1   
18         0        18250.0         53   среднее             1   
24         1        18250.0         57   среднее             1   
25         0        18250.0         67   среднее             1   
30         1        18250.0         62   среднее             1   

            family_status  family_status_id gender income_type  debt  \
4        гражданский брак                 1      F   пенсионер     0   
18         вдовец / вдова                 2      F   пенсионер     0   
24  Не женат / не замужем                 4      F   пенсионер     0   
25        женат / замужем                 0      M   пенсионер     0   
30        женат / замужем                 0      F   пенсионер     0   

     total_income                                purpose  
4   158616.077870                        сыграть свадьбу  
18   56823.777243     на покупку подержанного автомобиля  
24  290547.235997  операции с коммерческой недвижимостью  
25   55112.757732                   покупка недвижимости  
30  171456.067993  операции с коммерческой недвижимостью

In [36]:
# Выводим данные о минимальном, среднем и максимальном возрасте трудоустройства заемщиков.

employment_age1 = data1[data1['days_employed'] > 0]['dob_years'] - (data1['days_employed'] / 365)

print(f"Минимальный возраст трудоустройства заемщика - {employment_age1.min():.2f} лет")  # -28.00 лет
print(f"Средний возраст трудоустройства заемщика - {employment_age1.mean():.2f} лет")     # 9.42 лет
print(f"Максимальный возраст трудоустройства заемщика - {employment_age1.max():.2f} лет") # 24.00 лет

Минимальный возраст трудоустройства заемщика - -28.00 лет
Средний возраст трудоустройства заемщика - 9.42 лет
Максимальный возраст трудоустройства заемщика - 24.00 лет


Как видим из столбцов "dob_years" и "days_employed", у многих разница между возрастом и максимальным стажем (возраст трудоустройства) слишком маленькая. А минимальное значение вообще отрицательное.

Выясним минимальный возраст этих двух категорий заемщиков (пенсионеров и безработных).

In [37]:
print("Минимальный возраст заемщиков с большим значением стажа -",
      data1[data1['days_employed'] > 0]['dob_years'].min(), "года")

Минимальный возраст заемщиков с большим значением стажа - 22 года


Посмотрим, не портят ли картину двое безработных.

In [38]:
# Выводим уникальные значения возрастов безработных заемщиков, отсортированных в порядке их возрастания.
# Слева - возраст, справа - число заемщиков такого возраста.

data1[data1['income_type'] == 'безработный']['dob_years'].value_counts().sort_index()

31    1
45    1
Name: dob_years, dtype: int64

Выходит, что с 22 лет начинается возраст самих пенсионеров.


Откорректируем стаж, чтобы возраст трудоустройства вернулся в рамки.
Если разница между возрастом заемщика (в годах) и максимальным стажем (50 лет) составила менее 18 лет, необходимо указать стаж, равный разнице между возрастом (в днях) и 18 годами (6570 днями).

In [39]:
# Обновляем возраст тех, у кого стаж получается нереально большим, так чтобы возраст трудоустройства не был больше 18 лет.
# Выводим обновленные данные о минимальном, среднем и максимальном возрасте трудоустройства заемщиков.

data1.loc[(data1['days_employed'] > 0) & ((data1['dob_years'] - 50) < 18),
          'days_employed'] = data1['dob_years'] * 365 - 18 * 365

employment_age1 = data1[data1['days_employed'] > 0]['dob_years'] - (data1['days_employed'] / 365)

print(f"Минимальный возраст трудоустройства заемщика - {employment_age1.min():.2f} лет")  # 18.00 лет
print(f"Средний возраст трудоустройства заемщика - {employment_age1.mean():.2f} лет")     # 18.14 лет
print(f"Максимальный возраст трудоустройства заемщика - {employment_age1.max():.2f} лет") # 24.00 лет

Минимальный возраст трудоустройства заемщика - 18.00 лет
Средний возраст трудоустройства заемщика - 18.14 лет
Максимальный возраст трудоустройства заемщика - 24.00 лет


Теперь поменяем отрицательные значения в стаже на положительные.

In [40]:
print("Количество отрицательных значений в столбце 'days_employed' до замены -", 
      data1[data1['days_employed'] < 0]['days_employed'].count())

Количество отрицательных значений в столбце 'days_employed' до замены - 15906


In [41]:
data1.loc[data1['days_employed'] < 0,'days_employed'] = - data1['days_employed']
print("Количество отрицательных значений в столбце 'days_employed' после замены -", 
      data1[data1['days_employed'] < 0]['days_employed'].count())

Количество отрицательных значений в столбце 'days_employed' после замены - 0


In [42]:
# Обновляем возраст всех заемщиков, так чтобы возраст трудоустройства не был больше 18 лет.
# Выводим обновленные данные о минимальном, среднем и максимальном возрасте трудоустройства заемщиков.

data1.loc[((data1['dob_years'] - 50) < 18),'days_employed'] = data1['dob_years'] * 365 - 18 * 365

employment_age1 = data1['dob_years'] - data1['days_employed'] / 365

# РЕЗУЛЬТАТ ПО ВАРИАНТУ 2a
print(f"Минимальный возраст трудоустройства заемщика - {employment_age1.min():.2f} лет")   # 18.00 лет
print(f"Средний возраст трудоустройства заемщика - {employment_age1.mean():.2f} лет")      # 18.09 лет
print(f"Максимальный возраст трудоустройства заемщика - {employment_age1.max():.2f} лет")  # 70.40 лет

Минимальный возраст трудоустройства заемщика - 18.00 лет
Средний возраст трудоустройства заемщика - 18.09 лет
Максимальный возраст трудоустройства заемщика - 70.40 лет


Полученные показатели довольно сомнительны.
Причиной, вероятнее всего, послужил максимальный стаж в 50 лет, взятый за основу расчета.

#### Шаг 3

__Вариант 2b.__

In [43]:
# Создаем копию датафрейма для проверки Варианта 2b.

data2 = data.copy()

Найдем средний стаж остальных категорий заемщиков (кроме пенсионеров и безработных).

In [44]:
print(f"Средний стаж заемщиков, кроме пенсионеров и безработных, "
      f"- {(data2[data2['days_employed'] < 0]['days_employed'].mean() / (-365)):.2f} лет")

Средний стаж заемщиков, кроме пенсионеров и безработных, - 6.45 лет


Сформируем Series c данными о возрастах трудоустройства этих заемщиков.

In [45]:
# По каждому из этой группы заемщиков находим возраст трудоустройства (разницу между возрастом и стажем), 
# при условии, что он составляет не менее 18 лет.

neg_days_employment_age = data2[
    (data2['days_employed'] < 0) 
    & (data2['dob_years'] - (data2['days_employed'] / (-365)) >= 18)
]['dob_years'] - (data2['days_employed'] / (-365))

neg_days_employment_age.describe()

count    15496.000000
mean        34.001154
std          9.937833
min         18.000321
25%         25.872307
50%         32.592106
75%         40.912223
max         70.400083
dtype: float64

Из описания видно, что средний возраст трудоустройства составил 34 года. Попробуем использовать его для обновления данных о стаже пенсионеров и безработных.

Поскольку минимальный возраст в этих категориях - 22 года, необходимо учесть, что для расчета среднего будут взяты только те заемщики, которым уже исполнилось 34.

Обновим столбец c данными о стаже пенсионеров и безработных.

In [46]:
# По каждому из этой группы заемщиков находим трудовой стаж (разницу между текущим возрастом и возрастом трудоустройства), 
# при условии, что он составляет не менее 34 лет.

data2['days_employed'] = data2[(data2['days_employed'] > 0) & (data2['dob_years'] >= 34)]['dob_years'] * 365 - 34 * 365
data2['days_employed'].describe() / 365

count     9.402740
mean     25.531469
std       6.057978
min       0.000000
25%      22.000000
50%      26.000000
75%      30.000000
max      40.000000
Name: days_employed, dtype: float64

По описанию видно, что средний по этой группе заемщиков стаж составил около 25.5 лет, а максимальный - 40 лет.
Эти данные более реалистичны, чем  в Варианте 2а.

#### Шаг 4

Повторим все, как в Варианте 2а, но теперь подставим полученный в результате расчетов максимальный стаж 40 лет, вместо 50. 

In [47]:
# Создаем еще одну копию датафрейма для окончания проверки Варианта 2b.

data3 = data.copy()

In [48]:
# Заменяем все положительные значения трудового стажа на 14600 дней (т.е. 40 лет).
# Обновляем возраст тех, у кого стаж получается нереально большим, так чтобы возраст трудоустройства не был больше 18 лет.

data3.loc[data3['days_employed'] > 0,'days_employed'] = 40 * 365
data3.loc[(data3['days_employed'] > 0) 
          & ((data3['dob_years'] - 40) < 18),
          'days_employed'] = data3['dob_years'] * 365 - 18 * 365

employment_age3 = data3[data3['days_employed'] > 0]['dob_years'] - (data3['days_employed'] / 365)

print(f"Минимальный возраст трудоустройства заемщика - {employment_age3.min():.2f} лет")   # 18.00 лет
print(f"Средний возраст трудоустройства заемщика - {employment_age3.mean():.2f} лет")      # 21.21 лет
print(f"Максимальный возраст трудоустройства заемщика - {employment_age3.max():.2f} лет")  # 34.00 лет

Минимальный возраст трудоустройства заемщика - 18.00 лет
Средний возраст трудоустройства заемщика - 21.21 лет
Максимальный возраст трудоустройства заемщика - 34.00 лет


Обновленные данные по возрастам трудоустройства оказались наиболее близкими к реальным.

Теперь поменяем отрицательные значения в стаже на положительные.

In [49]:
print("Количество отрицательных значений в столбце 'days_employed' до замены -", 
      data3[data3['days_employed'] < 0]['days_employed'].count())

Количество отрицательных значений в столбце 'days_employed' до замены - 15906


In [50]:
data3.loc[data3['days_employed'] < 0,'days_employed'] = - data3['days_employed']
print("Количество отрицательных значений в столбце 'days_employed' после замены -", 
      data3[data3['days_employed'] < 0]['days_employed'].count())

Количество отрицательных значений в столбце 'days_employed' после замены - 0


In [51]:
# Обновляем возраст всех заемщиков, так чтобы возраст трудоустройства не был больше 18 лет.
# Выводим обновленные данные о минимальном, среднем и максимальном возрасте трудоустройства заемщиков.

data3.loc[((data3['dob_years'] - 40) < 18),'days_employed'] = data3['dob_years'] * 365 - 18 * 365

employment_age3 = data3['dob_years'] - data3['days_employed'] / 365

# РЕЗУЛЬТАТ ПО ВАРИАНТУ 2b
print(f"Минимальный возраст трудоустройства заемщика - {employment_age3.min():.2f} лет")   # 10.62 лет
print(f"Средний возраст трудоустройства заемщика - {employment_age3.mean():.2f} лет")      # 19.83 лет
print(f"Максимальный возраст трудоустройства заемщика - {employment_age3.max():.2f} лет")  # 70.40 лет

Минимальный возраст трудоустройства заемщика - 10.62 лет
Средний возраст трудоустройства заемщика - 19.83 лет
Максимальный возраст трудоустройства заемщика - 70.40 лет


In [52]:
# Выводим полученные данные о возрастах трудоустройства заемщиков, отсортиорванные в порядке возрастания.
# Слева - индексы в датафрейме, справа - возраст трудоустройства.

(data3['dob_years'] - data3['days_employed'] / 365).sort_values().head(10)

16335    10.619315
4299     12.738183
17838    14.439179
7329     14.538431
1539     15.751565
4321     17.786133
13815    18.000000
13816    18.000000
13817    18.000000
13818    18.000000
dtype: float64

Из рамок возраста трудоустройства выбиваются всего несколько данных, где он у заемщиков меньше 18, что на результат не повлияет.

#### Шаг 5

_Вывод:_
    
Варианты 2а и 2b дали примерно одинаковые результаты по среднему возрасту трудоустройства от 18 до 20 лет. В то время как в Варианте 1 среднее составило около 31 года.
Минимальные и максимальные значения примерно одинаковые, а вот распределение значений в Вариантах 2а и 2b неравномерное.

In [53]:
# Распределение статистических значений

print(employment_age0.describe()) # 1
print()
print(employment_age1.describe()) # 2a
print()
print(employment_age3.describe()) # 2b

count    19351.000000
mean        31.250961
std         10.571710
min         18.000000
25%         22.409551
50%         29.358876
75%         38.562783
max         70.400083
dtype: float64

count    21500.000000
mean        18.090541
std          1.718892
min         18.000000
25%         18.000000
50%         18.000000
75%         18.000000
max         70.400083
dtype: float64

count    21170.000000
mean        19.831920
std          6.912485
min         10.619315
25%         18.000000
50%         18.000000
75%         18.000000
max         70.400083
dtype: float64


Выбор очевиден в пользу более простого Варианта 1.

In [54]:
# Сохраняем выбранный вариант снова в переменную "data". 
# Выводим первые несколько строк датафрейма.

data = data0

data.head()

children  days_employed  dob_years education  education_id  \
0         1    8437.673028         42    высшее             0   
1         1    4024.803754         36   среднее             1   
2         0    5475.000000         33   Среднее             1   
3         3    4124.747207         32   среднее             1   
4         0   12775.000000         53   среднее             1   

      family_status  family_status_id gender income_type  debt   total_income  \
0   женат / замужем                 0      F   сотрудник     0  253875.639453   
1   женат / замужем                 0      F   сотрудник     0  112080.014102   
2   женат / замужем                 0      M   сотрудник     0  145885.952297   
3   женат / замужем                 0      M   сотрудник     0  267628.550329   
4  гражданский брак                 1      F   пенсионер     0  158616.077870   

                      purpose  
0               покупка жилья  
1     приобретение автомобиля  
2               покупка жилья  
3  дополнительное образование  
4             сыграть свадьбу

In [55]:
# Удаляем все копии датафрейма.

try:
    del data0
    del data1
    del data2
    del data3

    print('Все копии датафрейма удалены.')

except:
    
    print('Видимо, Вы уже удалили эти копии датафрейма.')

Все копии датафрейма удалены.


Аномалии в столбце "days_employed" исправлены.

#### Шаг 6

Заполним оставшиеся пустые ячейки в столбце "days_employed" медианными значениями по каждому типу занятости.

In [56]:
# Просматриваем информацию о датафрейме перед заполнением пустых ячеек.

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      21525 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


In [57]:
# Заполняем пустые ячейки медианными значениями и выводим обновленную информацию о таблице. 

data_by_days = data.groupby('income_type')['days_employed'].transform('median')
data['days_employed'] = data['days_employed'].fillna(data_by_days)

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   children          21525 non-null  int64  
 1   days_employed     21525 non-null  float64
 2   dob_years         21525 non-null  int64  
 3   education         21525 non-null  object 
 4   education_id      21525 non-null  int64  
 5   family_status     21525 non-null  object 
 6   family_status_id  21525 non-null  int64  
 7   gender            21525 non-null  object 
 8   income_type       21525 non-null  object 
 9   debt              21525 non-null  int64  
 10  total_income      21525 non-null  float64
 11  purpose           21525 non-null  object 
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


### Cтолбец "children"

Заменим значения "20" в столбце "children" на "2", удалим строки с "-1" .

In [58]:
# Заменяем значения "20"  на "2".

data['children'] = data['children'].replace(20, 2)

print(data['children'].value_counts())

 0    14149
 1     4818
 2     2131
 3      330
-1       47
 4       41
 5        9
Name: children, dtype: int64


In [59]:
# Удаляем строки со значением "-1" и обновляем индексы датафрейма.

data = data.drop(data[data['children'] == -1].index).reset_index(drop=True)

print(data['children'].value_counts())

0    14149
1     4818
2     2131
3      330
4       41
5        9
Name: children, dtype: int64


In [60]:
# Выводим последние несколько строк датафрейма, чтобы убедиться, что его индексы обновились.

data.tail()

children  days_employed  dob_years education  education_id  \
21473         1    4529.316663         43   среднее             1   
21474         0   14330.725172         67   среднее             1   
21475         1    2113.346888         38   среднее             1   
21476         3    3112.481705         38   среднее             1   
21477         2    1984.507589         40   среднее             1   

          family_status  family_status_id gender income_type  debt  \
21473  гражданский брак                 1      F   компаньон     0   
21474   женат / замужем                 0      F   пенсионер     0   
21475  гражданский брак                 1      M   сотрудник     1   
21476   женат / замужем                 0      M   сотрудник     1   
21477   женат / замужем                 0      F   сотрудник     0   

        total_income                       purpose  
21473  224791.862382             операции с жильем  
21474  155999.806512          сделка с автомобилем  
21475   89672.561153                  недвижимость  
21476  244093.050500  на покупку своего автомобиля  
21477   82047.418899         на покупку автомобиля

Значения в столбце "children" исправлены, строки удалены, индексы обновлены. 

Снова вызовем таблицу с описанием численных данных.

In [61]:
data.describe()

children  days_employed     dob_years  education_id  \
count  21478.000000   21478.000000  21478.000000  21478.000000   
mean       0.478583    4417.279356     43.497253      0.817208   
std        0.755962    5038.262559     12.232334      0.548371   
min        0.000000      24.141633     19.000000      0.000000   
25%        0.000000    1024.461713     34.000000      1.000000   
50%        0.000000    1987.915804     43.000000      1.000000   
75%        1.000000    5303.620304     53.000000      1.000000   
max        5.000000   16738.158823     75.000000      4.000000   

       family_status_id          debt  total_income  
count      21478.000000  21478.000000  2.147800e+04  
mean           0.972577      0.081013  1.652515e+05  
std            1.420338      0.272862  9.809959e+04  
min            0.000000      0.000000  2.066726e+04  
25%            0.000000      0.000000  1.077766e+05  
50%            0.000000      0.000000  1.425944e+05  
75%            1.000000      0.000000  1.956350e+05  
max            4.000000      1.000000  2.265604e+06

Как видим, все указанные аномалии устранены. Все "NaN" по датафрейму заполнены, ошибки исправлены.

### Изменение типов данных

Замениим вещественный тип данных в столбцах "days_employed" и "total_income" на целочисленный.

In [62]:
# Меняем значения ячеек в столбцах "days_employed" и "total_income" с float64 на int64.
# Выводим обновленную информацию.

data['days_employed'] = data['days_employed'].astype('int')
data['total_income'] = data['total_income'].astype('int')

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21478 entries, 0 to 21477
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   children          21478 non-null  int64 
 1   days_employed     21478 non-null  int32 
 2   dob_years         21478 non-null  int64 
 3   education         21478 non-null  object
 4   education_id      21478 non-null  int64 
 5   family_status     21478 non-null  object
 6   family_status_id  21478 non-null  int64 
 7   gender            21478 non-null  object
 8   income_type       21478 non-null  object
 9   debt              21478 non-null  int64 
 10  total_income      21478 non-null  int32 
 11  purpose           21478 non-null  object
dtypes: int32(2), int64(5), object(5)
memory usage: 1.8+ MB


In [63]:
# Выводим первые несколько строк датафрейма, чтобы убедиться, что значения в указанных столбцах стали целочисленными.

data.head()

children  days_employed  dob_years education  education_id  \
0         1           8437         42    высшее             0   
1         1           4024         36   среднее             1   
2         0           5475         33   Среднее             1   
3         3           4124         32   среднее             1   
4         0          12775         53   среднее             1   

      family_status  family_status_id gender income_type  debt  total_income  \
0   женат / замужем                 0      F   сотрудник     0        253875   
1   женат / замужем                 0      F   сотрудник     0        112080   
2   женат / замужем                 0      M   сотрудник     0        145885   
3   женат / замужем                 0      M   сотрудник     0        267628   
4  гражданский брак                 1      F   пенсионер     0        158616   

                      purpose  
0               покупка жилья  
1     приобретение автомобиля  
2               покупка жилья  
3  дополнительное образование  
4             сыграть свадьбу

Изменение типов данных выполнено.

### Удаление дубликатов

#### Полные дубликаты

Перед удалением посчитаем суммарное количество дубликатов в таблице.

In [64]:
print("Общее количество дубликатов в датафрейме -", data.duplicated().sum())

Общее количество дубликатов в датафрейме - 54


Отобразим некоторые дублирующиеся строки таблицы. Для наглядности сортируем по столбцу "days_employed", т.к. это один из столбцов с наиболее уникальными значениями. 

In [65]:
# Выводим первые 10 строк таблицы, отсортированной по столбцу с данными о трудовом стаже, по возрастанию.

data[data.duplicated()].sort_values(by=['days_employed']).head(10)

children  days_employed  dob_years education  education_id  \
17734         1           1530         40   среднее             1   
17341         0           1530         54    высшее             0   
19344         0           1530         38    высшее             0   
13846         1           1530         31   среднее             1   
10671         0           1530         40   среднее             1   
2841          0           1571         41   среднее             1   
13910         0           1571         44   среднее             1   
14799         0           1571         50   среднее             1   
15058         0           1571         58   среднее             1   
15154         0           1571         60   среднее             1   

               family_status  family_status_id gender income_type  debt  \
17734       гражданский брак                 1      F   компаньон     0   
17341        женат / замужем                 0      M   компаньон     0   
19344       гражданский брак                 1      F   компаньон     0   
13846        женат / замужем                 0      F   компаньон     0   
10671       гражданский брак                 1      F   компаньон     0   
2841         женат / замужем                 0      F   сотрудник     0   
13910        женат / замужем                 0      F   сотрудник     0   
14799  Не женат / не замужем                 4      F   сотрудник     0   
15058       гражданский брак                 1      M   сотрудник     0   
15154        женат / замужем                 0      M   сотрудник     0   

       total_income                                purpose  
17734        172357       строительство жилой недвижимости  
17341        172357  операции с коммерческой недвижимостью  
19344        172357                  на проведение свадьбы  
13846        172357                          покупка жилья  
10671        172357                        сыграть свадьбу  
2841         142594                покупка жилья для семьи  
13910        142594                приобретение автомобиля  
14799        142594                           недвижимость  
15058        142594                  на проведение свадьбы  
15154        142594                   покупка недвижимости

Возможная причина возникновения этих дубликатов - задвоение данных в результате технического сбоя и/или человеческого фактора.

Удаляем дубликаты.

In [66]:
data = data.drop_duplicates()

Проверим еще раз их наличие.

In [67]:
print("Общее количество дубликатов в датафрейме -", data.duplicated().sum())

Общее количество дубликатов в датафрейме - 0


#### Неявные дубликаты

Будем искать неявные дубликаты в столбцах с категориальными данными.

##### Столбец "education"

In [68]:
# Выводим уникальные значения в столбце "education".

data['education'].value_counts()

среднее                13674
высшее                  4702
СРЕДНЕЕ                  768
Среднее                  709
неоконченное высшее      667
ВЫСШЕЕ                   272
Высшее                   268
начальное                250
Неоконченное высшее       47
НЕОКОНЧЕННОЕ ВЫСШЕЕ       29
НАЧАЛЬНОЕ                 17
Начальное                 15
ученая степень             4
Ученая степень             1
УЧЕНАЯ СТЕПЕНЬ             1
Name: education, dtype: int64

Чтобы узнать точное число категорий, посмотрим уникальные данные столбца "education_id".

In [69]:
# Выводим уникальные значения в столбце "education_id".

data['education_id'].value_counts()

1    15151
0     5242
2      743
3      282
4        6
Name: education_id, dtype: int64

Как видим, категорий всего 5. 

Логично предположить что это:
- начальное;
- среднее;
- неоконченное высшее;
- высшее;
- ученая степень.

Возможная причина появления неявных дубликатов - человеческий фактор. Скорее всего, данные были заполнены разными сотрудниками кредитного учреждения.
Прослеживается 3 разных почерка. Если все данные напечатать строчными буквами, то, скорее всего, одинаковые тексты, написанные тремя разными способами, станут полными дубликатами.

Произведем соответствующие замены, переведя все данные в нижний регистр, и проверим результат.

In [70]:
# Меняем все заглавные буквы в значениях ячеек столбца об образовании на строчные.
# Выводим получившиеся уникальные значения в столбце "education".

data['education'] = data['education'].str.lower()

data['education'].value_counts()

среднее                15151
высшее                  5242
неоконченное высшее      743
начальное                282
ученая степень             6
Name: education, dtype: int64

Как видим, количества уникальных значений в столбцах "education" и "education_id" полностью совпадают.

##### Столбец "family_status"

In [71]:
# Выводим уникальные значения в столбце "family_status".

data['family_status'].value_counts()

женат / замужем          12315
гражданский брак          4158
Не женат / не замужем     2805
в разводе                 1191
вдовец / вдова             955
Name: family_status, dtype: int64

In [72]:
# Выводим уникальные значения в столбце "family_status_id".

data['family_status_id'].value_counts()

0    12315
1     4158
4     2805
3     1191
2      955
Name: family_status_id, dtype: int64

Дубликатов здесь нет. Но желательно также внести исправления. Конкретно - строку "Не женат / не замужем" исправить на "холост / не замужем".

In [73]:
# Меняем все значения "Не женат / не замужем" в столбце "family_status" на "холост / не замужем".
# Выводим получившиеся уникальные значения в столбце.

data['family_status'] = data['family_status'].replace('Не женат / не замужем', 'холост / не замужем')

data['family_status'].value_counts()

женат / замужем        12315
гражданский брак        4158
холост / не замужем     2805
в разводе               1191
вдовец / вдова           955
Name: family_status, dtype: int64

Изменения произведены.

##### Столбец "gender"

In [74]:
# Выводим уникальные значения в столбце "gender".

data['gender'].value_counts()

F      14154
M       7269
XNA        1
Name: gender, dtype: int64

В этом столбце есть одно неопознанное значение "XNA". Просмотрим данные об этом заемщике.

In [75]:
# Выводим строку с данными о заемщике "XNA".

data[data['gender'] == 'XNA']

children  days_employed  dob_years            education  education_id  \
10675         0           2190         24  неоконченное высшее             2   

          family_status  family_status_id gender income_type  debt  \
10675  гражданский брак                 1    XNA   компаньон     0   

       total_income               purpose  
10675        203905  покупка недвижимости

Возможно, имела место ошибка или просто заемщик не пожелал указывать пол.
Отнести его по косвенным данным к какому-либо из полов сложно. 

Можем заменить на "F", так как количество "F" больше (соответственно, верятность отнесения к этой категории статистически выше). 
Также можно оставить его или вовсе удалить.

Выберем последнее.

In [76]:
# Удаляем строку со значением "XNA" и обновляем индексы датафрейма.

data = data.drop(data[data['gender'] == 'XNA'].index).reset_index(drop=True)

Кроме того, запишем значения кириллицей: "М" и "Ж".

In [77]:
# Меняем "F" в столбце "gender" на "Ж".
# Меняем латинскую "M" на кириллическую "М".
# Выводим обновленные уникальные значения в столбце.

data['gender'] = data['gender'].replace('F', 'Ж')
data['gender'] = data['gender'].replace('M', 'М')

data['gender'].value_counts()

Ж    14154
М     7269
Name: gender, dtype: int64

In [78]:
# Выводим последние 5 строк датафрейма для проверки изменений значений столбца "gender"
# и обновления индексов датафрейма.

data.tail()

children  days_employed  dob_years education  education_id  \
21418         1           4529         43   среднее             1   
21419         0          14330         67   среднее             1   
21420         1           2113         38   среднее             1   
21421         3           3112         38   среднее             1   
21422         2           1984         40   среднее             1   

          family_status  family_status_id gender income_type  debt  \
21418  гражданский брак                 1      Ж   компаньон     0   
21419   женат / замужем                 0      Ж   пенсионер     0   
21420  гражданский брак                 1      М   сотрудник     1   
21421   женат / замужем                 0      М   сотрудник     1   
21422   женат / замужем                 0      Ж   сотрудник     0   

       total_income                       purpose  
21418        224791             операции с жильем  
21419        155999          сделка с автомобилем  
21420         89672                  недвижимость  
21421        244093  на покупку своего автомобиля  
21422         82047         на покупку автомобиля

##### Столбец "income_type".

In [79]:
# Выводим уникальные значения в столбце "income_type".

data['income_type'].value_counts()

сотрудник          11065
компаньон           5070
пенсионер           3829
госслужащий         1453
безработный            2
предприниматель        2
студент                1
в декрете              1
Name: income_type, dtype: int64

В этом столбце дубликатов и ошибок нет.

##### Столбец "debt"

In [80]:
# Выводим уникальные значения в столбце "debt".

data['debt'].value_counts()

0    19683
1     1740
Name: debt, dtype: int64

Здесь также все в порядке.

##### Столбец "purpose"

In [81]:
# Выводим уникальные значения в столбце "purpose".

data['purpose'].value_counts()

свадьба                                   793
на проведение свадьбы                     772
сыграть свадьбу                           768
операции с недвижимостью                  673
покупка коммерческой недвижимости         662
покупка жилья для сдачи                   651
операции с жильем                         651
операции с коммерческой недвижимостью     649
жилье                                     645
покупка жилья                             643
покупка жилья для семьи                   638
строительство собственной недвижимости    634
недвижимость                              632
операции со своей недвижимостью           624
строительство жилой недвижимости          622
строительство недвижимости                619
покупка своего жилья                      619
покупка недвижимости                      617
ремонт жилью                              606
покупка жилой недвижимости                604
на покупку своего автомобиля              504
заняться высшим образованием      

В данном столбце причиной образования такого количества дубликатов является недостаточная проработака программы для ввода данных. Цели кредита изначально не были объединены в категории. Поэтому были занесены в разное время по-разному, возможно, со слов клиентов.

В предыдущих столбцах для явных дубликатов были использованы методы .duplicated() (поиск дубликатов) и drop_duplicates() (удаление дубликатов).
Для неявных - .value_counts() (подсчет уникальных значений), а также .str.lower() (перевод в нижний регистр) и .replace() (замена значений).

Однако для данных в столбце "purpose" указанные методы не подойдут. Вернемся к его обработке позже.

### Формирование дополнительных датафреймов-словарей

In [82]:
# Выводим первые несколько строк датафрейма.

data.head()

children  days_employed  dob_years education  education_id  \
0         1           8437         42    высшее             0   
1         1           4024         36   среднее             1   
2         0           5475         33   среднее             1   
3         3           4124         32   среднее             1   
4         0          12775         53   среднее             1   

      family_status  family_status_id gender income_type  debt  total_income  \
0   женат / замужем                 0      Ж   сотрудник     0        253875   
1   женат / замужем                 0      Ж   сотрудник     0        112080   
2   женат / замужем                 0      М   сотрудник     0        145885   
3   женат / замужем                 0      М   сотрудник     0        267628   
4  гражданский брак                 1      Ж   пенсионер     0        158616   

                      purpose  
0               покупка жилья  
1     приобретение автомобиля  
2               покупка жилья  
3  дополнительное образование  
4             сыграть свадьбу

Создадим из исходного датафрейма два новых: для столбцов с данными об образовании и семейном положении, соответственно.

__1.__ Образование (столбцы "education" и "education_id").

Создадим новый датафрейм из указанных столбцов, удалив дубликаты и убрав старые индексы. 
Для удобства расположим "education_id" слева.

In [83]:
# Создаем новый датафрейм education из столбцов "education" и "education_id".
# Выведем созданную таблицу.

education = (data[['education_id', 'education']]
             .drop_duplicates()
             .reset_index(drop=True)
             .set_index('education_id')
            )
display(education)

education
education_id                     
0                          высшее
1                         среднее
2             неоконченное высшее
3                       начальное
4                  ученая степень

__2.__ Семейное положение (столбцы "family_status" и "family_status_id").

Те же действия произведем и с этими столбцами.

In [84]:
# Создаем новый датафрейм family_status из столбцов "family_status" и "family_status_id".
# Выведем созданную таблицу.

family_status = (data[['family_status_id', 'family_status']]
                 .drop_duplicates()
                 .reset_index(drop=True)
                 .set_index('family_status_id')
                )
display(family_status)

family_status
family_status_id                     
0                     женат / замужем
1                    гражданский брак
2                      вдовец / вдова
3                           в разводе
4                 холост / не замужем

Удалим столбцы "education" и "family_status" из исходной таблицы.

In [85]:
# Удаляем столбцы "education" и "family_status" из исходного датафрейма.
# Выведем первые строки датафрейма.

data = data.drop(['education', 'family_status'], axis=1)
data.head()

children  days_employed  dob_years  education_id  family_status_id gender  \
0         1           8437         42             0                 0      Ж   
1         1           4024         36             1                 0      Ж   
2         0           5475         33             1                 0      М   
3         3           4124         32             1                 0      М   
4         0          12775         53             1                 1      Ж   

  income_type  debt  total_income                     purpose  
0   сотрудник     0        253875               покупка жилья  
1   сотрудник     0        112080     приобретение автомобиля  
2   сотрудник     0        145885               покупка жилья  
3   сотрудник     0        267628  дополнительное образование  
4   пенсионер     0        158616             сыграть свадьбу

Столбцы удалены.

### Категоризация дохода

Создадим новый столбец "total_income_category", в котором будут отображаться данные о категориях доходов из столбца "total_income":

0 - 30000 — "E";

30001 - 50000 — "D";

50001 - 200000 — "C";

200001 - 1000000 — "B";

1000001 и выше — "A".

Можно это сделать двумя способами. Сначала попробуем обойтись без написания дополнительных функций.

In [86]:
# Создаем новый столбец "total_income_category", вставляем его после восьмого слева столбца.
# Заполняем ячейки созданного столбца названиями категорий (А-Е), соответственно указанному выше правилу.

data.insert(9, 'total_income_category', '')

data.loc[data['total_income'] <= 30000, 'total_income_category'] = 'E'
data.loc[(data['total_income'] > 30000) & (data['total_income'] <= 50000), 'total_income_category'] = 'D'
data.loc[(data['total_income'] > 50000) & (data['total_income'] <= 200000), 'total_income_category'] = 'C'
data.loc[(data['total_income'] > 200000) & (data['total_income'] <= 1000000), 'total_income_category'] = 'B'
data.loc[data['total_income'] > 1000000, 'total_income_category'] = 'A'

Проверим правильность работы кода на примере одной из категорий.

In [87]:
# Проверяем, правильно ли работает код, выведя полученную по заданным условиям категорию.

display(data[(data['total_income'] > 30000) & (data['total_income'] <= 50000)]['total_income_category'].unique())

array(['D'], dtype=object)

Все верно. Просмотрим полученную таблицу.

In [88]:
# Первые 5 строк обновленного датафрейма

data.head()

children  days_employed  dob_years  education_id  family_status_id gender  \
0         1           8437         42             0                 0      Ж   
1         1           4024         36             1                 0      Ж   
2         0           5475         33             1                 0      М   
3         3           4124         32             1                 0      М   
4         0          12775         53             1                 1      Ж   

  income_type  debt  total_income total_income_category  \
0   сотрудник     0        253875                     B   
1   сотрудник     0        112080                     C   
2   сотрудник     0        145885                     C   
3   сотрудник     0        267628                     B   
4   пенсионер     0        158616                     C   

                      purpose  
0               покупка жилья  
1     приобретение автомобиля  
2               покупка жилья  
3  дополнительное образование  
4             сыграть свадьбу

Теперь создадим функцию, с помощью которой можно будет проверить правильность условий, прежде чем применять в датафрейме.

In [89]:
# Функция, возвращающая название категории в зависимости от величины дохода

def income_group(income):
    if income <= 30000:
        return 'E'
    if income > 30000 and income <= 50000:
        return 'D'
    if income > 50000 and income <= 200000:
        return 'C'
    if income > 200000 and income <= 1000000:
        return 'B'
    return 'A'

Можно проверить работоспособность функции, введя любые числа в качестве аргумента.

In [90]:
# Вносим произвольное целое число в качестве аргумента в income_group() и получаем соответствующую категорию доходов. 

print(f'Указанный доход соответствует категории "{income_group(100000)}".')

Указанный доход соответствует категории "C".


Применим функцию к новому столбцу. Старый при этом не будем удалять.

In [91]:
# Применяем созданную функцию income_group() к столбцу "total_income".

data['total_income_category1'] = data['total_income'].apply(income_group)

Взглянем на оба столбца вместе, чтобы визуально сравнить их.

In [92]:
# Выводим "total_income_category" и "total_income_category1" (первые 10 строк).

data[['total_income_category','total_income_category1']].head(10)

total_income_category total_income_category1
0                     B                      B
1                     C                      C
2                     C                      C
3                     B                      B
4                     C                      C
5                     B                      B
6                     B                      B
7                     C                      C
8                     C                      C
9                     C                      C

Проверим, есть ли несовпадения категорий в каких-либо местах.

In [93]:
# Находим количество несовпадений между столбцами. При условии правильного прохождения по коду оно должно равняться нулю. 

non_match = data[data['total_income_category'] != data['total_income_category1']
                ]['total_income_category'].count()
print('Количество несовпадений равно', non_match)

Количество несовпадений равно 0


Можем удалить лишний столбец.

In [94]:
# Удаляем столбец "total_income_category1".

data = data.drop('total_income_category1', axis=1)

Просмотрим таблицу еще раз.

In [95]:
# Первые 5 строк обновленного датафрейма

data.head()

children  days_employed  dob_years  education_id  family_status_id gender  \
0         1           8437         42             0                 0      Ж   
1         1           4024         36             1                 0      Ж   
2         0           5475         33             1                 0      М   
3         3           4124         32             1                 0      М   
4         0          12775         53             1                 1      Ж   

  income_type  debt  total_income total_income_category  \
0   сотрудник     0        253875                     B   
1   сотрудник     0        112080                     C   
2   сотрудник     0        145885                     C   
3   сотрудник     0        267628                     B   
4   пенсионер     0        158616                     C   

                      purpose  
0               покупка жилья  
1     приобретение автомобиля  
2               покупка жилья  
3  дополнительное образование  
4             сыграть свадьбу

Категоризация дохода выполнена верно.

### Категоризация целей кредита

Создадим функцию, которая на основании данных из столбца "purpose" сформирует новый столбец "purpose_category", в который войдут выявленные категории целей.

Перед этим определим сами категории на основании уникальных значений целей.

In [96]:
# Выводим список уникальных значений в столбце "purpose".

data['purpose'].unique()

array(['покупка жилья', 'приобретение автомобиля',
       'дополнительное образование', 'сыграть свадьбу',
       'операции с жильем', 'образование', 'на проведение свадьбы',
       'покупка жилья для семьи', 'покупка недвижимости',
       'покупка коммерческой недвижимости', 'покупка жилой недвижимости',
       'строительство собственной недвижимости', 'недвижимость',
       'строительство недвижимости', 'на покупку подержанного автомобиля',
       'на покупку своего автомобиля',
       'операции с коммерческой недвижимостью',
       'строительство жилой недвижимости', 'жилье',
       'операции со своей недвижимостью', 'автомобили',
       'заняться образованием', 'сделка с подержанным автомобилем',
       'получение образования', 'автомобиль', 'свадьба',
       'получение дополнительного образования', 'покупка своего жилья',
       'операции с недвижимостью', 'получение высшего образования',
       'свой автомобиль', 'сделка с автомобилем',
       'профильное образование', 'высшее об

Уникальных категорий всего получается 4. Назовем их следующим образом:

`"операции с автомобилем"` - все, что содержит слово "автомобиль",

`"операции с недвижимостью"` - ... слова "недвижимость" и "жилье",

`"проведение свадьбы"` - ... слово "свадьба",

`"получение образования"` - ... слово "образование".

Указанные слова содержатся в разных формах, что необходимо учесть при поиске.

Для работы функции создадим словарь соответствий.

In [97]:
# Создаем словарь с подстрокой в качестве ключей и названием категории в качестве элементов.

purposes = {'автомобил':'операции с автомобилем', 
         'недвижимост':'операции с недвижимостью',
         'жиль':'операции с недвижимостью',
         'свадьб':'проведение свадьбы', 
         'образовани':'получение образования'
        }

Напишем функцию для подбора соответствующих элементов из словаря.

In [98]:
# Функция, которая возвращает значение элемента из словаря "purposes", 
# если находит в строке подстроку (сочетание букв ключа).

def matcher(text):
    for key in purposes:
        if text.find(key) >= 0:
            return purposes[key]

Создадим в датафрейме новый столбец "purpose_category" и заполним его данными с помощью функции matcher() и метода .apply().

In [99]:
# Добавляем в датафрейм столбец "purpose_category" и заполняем данными о категориях целей кредита.

data['purpose_category'] = data['purpose'].apply(matcher)

Проверим полученные уникальные значения.

In [100]:
# Проверяем полученные уникальные значения в столбце "purpose_category".

display(data['purpose_category'].value_counts())

операции с недвижимостью    10789
операции с автомобилем       4297
получение образования        4004
проведение свадьбы           2333
Name: purpose_category, dtype: int64

Убедимся, что пустых ячеек в таблице не осталось.

In [101]:
# Выводим информацию о датафрейме.

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21423 entries, 0 to 21422
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   children               21423 non-null  int64 
 1   days_employed          21423 non-null  int32 
 2   dob_years              21423 non-null  int64 
 3   education_id           21423 non-null  int64 
 4   family_status_id       21423 non-null  int64 
 5   gender                 21423 non-null  object
 6   income_type            21423 non-null  object
 7   debt                   21423 non-null  int64 
 8   total_income           21423 non-null  int32 
 9   total_income_category  21423 non-null  object
 10  purpose                21423 non-null  object
 11  purpose_category       21423 non-null  object
dtypes: int32(2), int64(5), object(5)
memory usage: 1.8+ MB


Просмотрим таблицу.

In [102]:
# Выводим первые 5 строк датафрейма.

data.head()

children  days_employed  dob_years  education_id  family_status_id gender  \
0         1           8437         42             0                 0      Ж   
1         1           4024         36             1                 0      Ж   
2         0           5475         33             1                 0      М   
3         3           4124         32             1                 0      М   
4         0          12775         53             1                 1      Ж   

  income_type  debt  total_income total_income_category  \
0   сотрудник     0        253875                     B   
1   сотрудник     0        112080                     C   
2   сотрудник     0        145885                     C   
3   сотрудник     0        267628                     B   
4   пенсионер     0        158616                     C   

                      purpose          purpose_category  
0               покупка жилья  операции с недвижимостью  
1     приобретение автомобиля    операции с автомобилем  
2               покупка жилья  операции с недвижимостью  
3  дополнительное образование     получение образования  
4             сыграть свадьбу        проведение свадьбы

Категоризация целей кредита выполнена верно.

## Ответы на вопросы

### Вопрос 1

_Есть ли зависимость между количеством детей и возвратом кредита в срок?_

Вызовем еще раз данные по количеству проблемных заемщиков из столбца "debt".

In [103]:
# Выводим уникальные значения ячеек в столбце "debt"

data['debt'].value_counts()

0    19683
1     1740
Name: debt, dtype: int64

In [104]:
print(f"Как видим, {data[data['debt'] == 1]['debt'].count()} "
      f"человек из {data.shape[0]} имели проблемы с возвратом кредита.")

Как видим, 1740 человек из 21423 имели проблемы с возвратом кредита.


Составим сводную таблицу по количеству детей. В качестве аргумента aggfunc возьмем среднее значение, т.к. именно доля проблемных заемщиков отразит реальную зависимость данных.

In [105]:
# Выводим сводную таблицу по количеству детей с отображением долей проблемных заемщиков по каждой группе.

data_pivot_children = data.pivot_table(index=None, columns='children', values='debt', aggfunc='mean')
data_pivot_children

children         0         1         2         3         4    5
debt      0.075358  0.092327  0.094925  0.081818  0.097561  0.0

Составим также таблицы с разделением заемщиков по полам. Одну - с долями проблемных заемщиков, вторую - с общим числом заемщиков. 

In [106]:
# Выводим сводную таблицу по полу и по количеству детей с отображением долей проблемных заемщиков по каждой группе.
# Выводим сводную таблицу по полу и по количеству детей с отображением количества заемщиков по каждой группе.

dp_children_gender = data.pivot_table(index='gender', 
                                      columns='children', 
                                      values='debt', 
                                      aggfunc='mean'
                                     )
display(dp_children_gender)

dp_children_gender_count = data.pivot_table(index='gender', 
                                            columns='children', 
                                            values='debt', 
                                            aggfunc='count'
                                           )
dp_children_gender_count

children         0         1         2         3         4    5
gender                                                         
Ж         0.062094  0.079391  0.105909  0.086735  0.035714  0.0
М         0.103018  0.115496  0.077576  0.074627  0.230769  0.0

children     0     1     2    3   4  5
gender                                
Ж         9534  3086  1303  196  28  7
М         4572  1723   825  134  13  2

__Выводы:__

1. Из таблиц явствует, что доля заемщиков с просроченными платежами по кредитам по варьируется от 7.5% до 9.8%.


- Меньше всех подвержены риску неплатежей заемщики без детей.


- После первого ребенка нагрузка на бюджет резко возрастает.


- Со вторым эта нагрузка чуть больше, но незначительно. Вероятно, сказывается господдержка.


- После третьего ребенка показатель снижается. Возможно, влияют дополнительные меры помощи от государства, а также родственников.


- С четверым ребенком нагрузка опять сильно возрастает.


- У заемщиков с пятью детьми просрочек нет. Но их самих тоже немного (всего 9 человек во всей базе), поэтому выводы делать трудно.

2. Из второй таблицы можно вынести более интересную информацию. В частности, что доля просрочек среди мужчин сильно отличается от аналогичного показателя у женщин.


- У женщин без детей кредитная дисциплина гораздо выше, чем у мужчин (6,2% просрочек против 10,3%). Необремененные семейными обязательствами мужчины более склонны к тратам и менее ответственны.


- У женщин с одним ребенком примерно такая же ситуация (7,9% против 11,5%). В целом у обоих проблем с кредитами чуть больше.


- После второго ребенка ситуация меняется. Очевидно, у женщин с двумя детьми становятся меньше возможностей зарабатывать, при этом расходы на детей удваиваются.


- С тремя детьми показатели немного выравниваются. У мужчин с двумя и тремя детьми показатель почти одинаков (7,8% и 7,5%, соответственно).


- А вот у заемщиков с четырьмя детьми происходит значительный перекос по половому признаку: многодетные отцы допускают просрочки в 23.1% случаев. При том, что у женщин с аналогичным положением он снижается до 3,6%. Если с двумя и тремя детьми материальное положение семей более-менее устойчивое, учитывая относительно умеренные расходы, а также меры поддержки, то дальше становится гораздо тяжелее. И все ложится на плечи основного кормильца семьи, т.е. чаще всего мужчины. Низкий показатель проблемной задолженности у многодетных матерей можно объяснить тем, что банки в принципе редко выдают кредиты таким категориям, а кому дают - тщательно проверяют платежеспособность. Учитывая, что такая заемщица только одна (28 х 0,036 = 1), ее показатель не должен влиять на решения кредитной организации.

Итог:

В целом нужно отметить, что среди женщин самыми худшими заемщиками являются те, у кого двое детей. 
А наиболее ответственные - это женщины еще не имеющие детей (или у кого уже дети повзрослели), и чуть менее - женщины с одним ребенком. Поскольку в последних двух подкатегориях более 12,5 тысяч человек (половина всей клиентской базы), можно сделать вывод, что в этой части система оценки кредитоспособности заемщика работает оптимально.


Среди мужчин ситуация обратная. Если не брать в расчет все тех же многодетных с четырьмя детьми, самые худшие заемщики - это мужчины с одним ребенком и бездетные. Самые ответственные - отцы троих и двоих детей.

Причина, на мой взгляд, в том, что женщины в целом более ответственные, но чем меньше у них забот о содержании детей, тем им легче справляться с этой ответственностью. Мужчины же изначально больше склонны к риску и тратам, но с появлением ребенка, а тем более второго-третьего, чувство ответственности за семью у них возрастает.

### Вопрос 2

_Есть ли зависимость между семейным положением и возвратом кредита в срок?_

Ввиду явного отличия между ситуациями с проблемной задолженностью у мужчин и женщин, далее их показатели будем рассматривать отдельно.

Составим сводные таблицы по семейному положению (с долями и общим количеством). 
Для удобства также выведем на экран датафрейм-словарь "family_status".

In [107]:
# Выводим сводную таблицу по полу и по семейному положению с отображением долей проблемных заемщиков по каждой группе.
# Выводим сводную таблицу по полу и по семейному положению с отображением количества заемщиков по каждой группе.
# Выводим датафрейм-словарь family_status.

dp_family_status_gender = data.pivot_table(index='family_status_id', 
                                           columns='gender', 
                                           values='debt', 
                                           aggfunc='mean'
                                          )
display(dp_family_status_gender)

dp_family_status_gender_count = data.pivot_table(index='family_status_id', 
                                                 columns='gender', 
                                                 values='debt', 
                                                 aggfunc='count'
                                                )
display(dp_family_status_gender_count)

family_status

gender                   Ж         М
family_status_id                    
0                 0.068311  0.087727
1                 0.081726  0.118683
2                 0.057778  0.200000
3                 0.065451  0.092664
4                 0.068327  0.144712

gender               Ж     М
family_status_id            
0                 7744  4571
1                 2851  1306
2                  900    55
3                  932   259
4                 1727  1078

family_status
family_status_id                     
0                     женат / замужем
1                    гражданский брак
2                      вдовец / вдова
3                           в разводе
4                 холост / не замужем

 __Выводы:__

1. Заемщики-женщины.


- Как видно из таблицы, среди женщин наименее склонны к просрочкам вдовы (5,8%). Обычно женщины, оказавшиеся без кормильца, больше беспокоятся за финансовую безопасность свою и детей. В целом они стараются поскорее погасить все кредитные обязательства. Или же это пожилые женщины, которые в целом более склонны к порядку и менее - к риску.


- Далее идут разведенные женщины (6,5%). Они тоже не чувствуют себя в безопасности, но тратят они чуть больше. Соответственно, на выплату кредитов остается меньше.


- Замужние женщины хоть и гораздо меньше вдов и разведенных беспокоятся об экономии в расходах, однако они не тянут в одиночку груз. Им в этом помогают мужья. Поэтому их показатель неплатежей не сильно выше - около 6,8%.


- На том же уровне показатель незамужних женщин. Они столько не тратят, но и доход их обычно меньше.


- Наименее ответственны по кредитным обязательствам женщины, состоящие в незарегистрированных отношениях (8,2%). Доходы у них примерно как у незамужних, возможно чуть больше. Однако траты у них чаще всего как у замужних, и не рассчитаны на возможные разрывы отношений и ухудшение финансового положения.

2. Заемщики-мужчины.

- Среди мужчин самый низкий показатель несвоевременных платежей у женатых мужчин (8,8%). Хотя он все равно выше, чем самый высокий у женщин. Как уже было сказано, с созданием семьи мужчины обычно становятся более ответственными.


- За ними следуют мужчины в разводе (9,3%). Чаще всего, если у такого мужчины есть дети, он не перестает быть ответственным. Если же он бездетный, по крайней мере с разводом его расходы уменьшаются и остается больше средств на погашение кредитов.


- У мужчин, находящися в гражданском браке уровень просрочек выше - 11,9%. Чаще всего в этом случае детей у них нет, а значит склонность к необоснованным расходам выше.


- Гораздо выше этот показатель у холостых мужчин - 14,5%. Холостой практический всегда бездетный. Соответственно, не обременненный заботами о семье и склонный к неоправданным и необдуманным тратам.


- Необычно высокий показатель оказался у вдовцов - 20%. Вдовцы в целом - явление редкое. Чаще всего вдовеют в результате неизлечимой болезни супруги. И обычно, это связано с высокими тратами на лечение с непредсказуемыми последствиями для кредитной истории.

Итог:

Самые добросовестные заемщицы - вдовы. И по статистике, чаще всего это женщины предпенсионного и пенсионного возраста. Показатели незамужних, замужних и разведенных примерно на одном уровне - средние. Худшие показатели у женщин, живущих в гражданском браке.

Среди мужчин наиболее привлекательные для кредитора заемщики - женатые и разведенные. Не очень надежные - в гражданском браке и холостые. И самые безнадежные - вдовцы (в среднем каждый пятый).

Причины все те же. У женщин дисциплина выше, когда они одиноки и независимы. У мужчин - когда они ответственны за семью, и есть кому ограничивать их траты.

### Вопрос 3

_Есть ли зависимость между уровнем дохода и возвратом кредита в срок?_

Составим аналогичные таблицы. Теперь возьмем в расчет доходы, с разбивкой по полам.

In [108]:
# Выводим сводную таблицу по полу и по ежемесячному доходу с отображением долей проблемных заемщиков по каждой группе.
# Выводим сводную таблицу по полу и по ежемесячному доходу с отображением количества заемщиков по каждой группе.

dp_total_income_category = data.pivot_table(index='gender', 
                                            columns='total_income_category', 
                                            values='debt', 
                                            aggfunc='mean'
                                           )
display(dp_total_income_category)

dp_total_income_category_count = data.pivot_table(index='gender', 
                                                  columns='total_income_category', 
                                                  values='debt', 
                                                  aggfunc='count'
                                                 )
display(dp_total_income_category_count)

total_income_category         A         B         C         D      E
gender                                                              
Ж                      0.000000  0.060606  0.073061  0.048701  0.125
М                      0.133333  0.082510  0.112090  0.146341  0.000

total_income_category   A     B      C    D   E
gender                                         
Ж                      10  2706  11114  308  16
М                      15  2327   4880   41   6

В качестве подсказки еще раз укажем диапазоны доходов у разных категорий (в тысячах ден.ед.):

__A__ - 1000 - __B__ - 200 - __C__ - 50 - __D__ - 30 - __E__

 __Выводы:__

В категориях "A" и "E" слишком мало заемщиков. Из них, судя по данным из двух таблиц, проблемы с платежами были только у двоих человек в каждой из категорий. Поэтому данные по ним брать в расчет не имеет смысла.

1. Заемщики-женщины.


- Судя по таблицам, меньше всех склонны к просрочкам женщины с доходом от 30 тыс. до 50 тыс. (4,9%). 


- После них - женщины, зарабатывающие от 200 тыс. до 1 млн. (6,1%).


- Наконец, те, у которых доход находится в диапазоне от 50 тыс. до 200 тыс., допускают задолженность чаще других (7,3%). 

2. Заемщики-мужчины.


- У мужчин снова данные отличаются. Самые благонаженые заемщики - мужчины с доходом от 200 тыс. до 1 млн. (8,3%).


- На втором месте - те, кто зарабатывает от 50 тыс. до 200 тыс. (11,2%).


- Хуже всего платят по кредитам мужчины с доходом 30 тыс. до 50 тыс. (14,6%).

Итог:

Лучшие заемщицы - небогатые женщины, худшие - женщины со средним достатком. 


Лучшие заемщики - богатые мужчины, худшие - с низким достатком.


Возможная причина в том, что женщины с небольшим достатком - это в основном или незамужние, или пожилые. Об этих категориях уже говорилось ранее как о наиболее добросовестных плательщиках. Но когда их доход вырастает, они начинают больше тратить и меньше беспокоиться (в основном - это замужние, с детьми). И только у богатых женщин (бизнес-вумен) этот показатель снова ниже благодаря их бережливости.

Среди мужчин же склонность к экономии и финансовому планированию растет прямо пропорционально доходам. Чем богаче - тем рациональнее рассчитывают свой бюджет.

###  Вопрос 4

_Как разные цели кредита влияют на его возврат в срок?_

Снова составим сводные таблицы, теперь уже учитывающие цели кредита.

In [109]:
# Выводим сводную таблицу по полу и по цели получения кредита с отображением долей проблемных заемщиков по каждой группе.
# Выводим сводную таблицу по полу и по цели получения кредита с отображением количества заемщиков по каждой группе.

dp_purpose_category = data.pivot_table(index='gender', 
                                       columns='purpose_category', 
                                       values='debt', 
                                       aggfunc='mean'
                                      )
display(dp_purpose_category)

dp_purpose_category_count = data.pivot_table(index='gender', 
                                             columns='purpose_category', 
                                             values='debt', 
                                             aggfunc='count'
                                            )
display(dp_purpose_category_count)

purpose_category  операции с автомобилем  операции с недвижимостью  \
gender                                                               
Ж                               0.081990                  0.062809   
М                               0.116424                  0.090860   

purpose_category  получение образования  проведение свадьбы  
gender                                                       
Ж                               0.07779            0.068790  
М                               0.12137            0.102228

purpose_category  операции с автомобилем  операции с недвижимостью  \
gender                                                               
Ж                                   2854                      7069   
М                                   1443                      3720   

purpose_category  получение образования  проведение свадьбы  
gender                                                       
Ж                                  2661                1570  
М                                  1343                 763

 __Выводы:__

1. Заемщики-женщины.


- Уровень просрочек у женщин, взявших кредит на покупку жилья самый низкий (6,3%). Вероятнее всего, это самостоятельные женщины, т.е. либо одинокие (любого достатка), либо замужние, но с высоким уровнем дохода и независимости.


- Чуть больше - 6,9% - у тех, кто обращались за кредитом для проведения свадьбы. Тут большинство, естественно, - незамужние.


- У женщин, берущих кредит на получение образования, процент выше, но не самый высокий - 7,8%. Очевидно, что они берут на второе образование, т.е. вполне осознавая все риски. Тем не менее это не самый низкий показатель, т.к. в большинстве своем такие заемщицы имеют семьи и, соответственно, их расходы и риски выше, чем у предыдущих подкатегорий.


- Наконец, наиболее высокий уровень просрочек (8,2%) у тех, кто взял кредит на покупку автомобиля. Это семейные люди, к проблемам которых добавляются еще и расходы на автокредит, бензин, запчасти, ремонт и т.д.

2. Заемщики-мужчины.


- И снова во всех категориях у мужчин этот показатель выше. Самый низкий у них - опять же, в случае ипотеки (9,0%). В целом, это всегда наименее рисковый вид кредитования, поскольку процентная ставка по нему обычно ниже, и берут такой кредит люди, имеющие семью и постоянный доход.


- На втором месте снова кредит на свадьбу (10,2%). Как говорилось ранее, после женитьбы у мужчин этот показатель стабилизируется.


- Далее идет автокредит (11,6%). Он также связан с дополнительными расходами и рисками, однако для многих мужчин - это еще и средство получения дохода (прямое или косвенное). Поэтому, в отличие от аналогичного показателя у женщин, здесь эта подкатегория не на последнем месте по надежности.


- Наконец, хуже всего платят мужчины, взявшие кредит на образование (12,1%). Возможно, многие из них менее серьезно относятся к учебе (а кто-то бросает ее) и возникающим дополнительным тратам.

Итог:

У заемщиков обоих полов лучше всего получается возвращать кредиты, взятые на покупку жилья и проведение свадьбы.

Причины: это важные события в жизни, и к ним (прежде всего, к жилью) подходят ответственно. Плюс, на них средства в основном находятся: в случае со свадьбой - люди еще не обременены большими семейными расходами, а ипотека всегда в приоритете в списке ежемесячно погашаемых кредитов, поскольку лишиться дома никто не хочет.

    
Хуже всего у женщин ситуация с автокредитом, а у мужчин - с кредитом на образование.

Причины: это дополнительные расходы и, соответственно, риски несвоевременного погашения. Для женщины автомобиль в итоге приносит больше затрат, чем для мужчин, для которых машина - это, прежде всего, актив. А с образованием наоборот - женщины к учебе в основном относятся более ответственно.

## Общие выводы

1. Женщина с худшим показателем надежности чаще всего надежнее мужчины с самым лучшим.


2. Самые надежные заемщицы - это женщины с невысоким доходом (до 50 тыс.), без иждивенцев, молодые или наоборот - пожилые, а также вдовы.
Наименее надежные - женщины с двумя детьми, со средним уровнем дохода, а также состоящие в гражданском браке.


3. Самые надежные заемщики - женатые мужчины с тремя (чуть менее - с двумя) детьми, с высоким доходом (от 200 тыс. до 1 млн.).
Наименее надежные - мужчины с одним ребенком и бездетные, холостые и вдовцы, с невысоким уровнем дохода (до 50 тыс.).


4. Самые безрисковые для кредитной организации направления кредитования - кредиты на операции с недвижимостью и проведение свадьбы.
В случае с женщинами рискованным является кредит на операции с автомобилем, а для мужчин - на получение образования.